name: 'Tritec Integrated Philippines, Inc'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38747
title: 'Tritec Integrated Philippines, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cce6e5'
    - '#6fc8d2'
    - '#81b3b5'
    - '#acc5c6'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
