name: 'Tritec Integrated Philippines, Inc'
favicon: null
layout_spectrum: 0.44807
typography_spectrum: 0.56091
title: 'Tritec Integrated Philippines, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#565657'
    - '#4bbec2'
    - '#a4dad6'
    - '#757576'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
