name: 'Tritec Integrated Philippines, Inc'
favicon: null
layout_spectrum: 0.05239
typography_spectrum: 0.89466
title: 'Tritec Integrated Philippines, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#565657'
    - '#4bbec2'
    - '#a4dad6'
    - '#757576'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
